blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/HomerusJa/gitmoji-pre-commit/discussions
  - name: ğŸ“š Documentation
    url: https://github.com/HomerusJa/gitmoji-pre-commit/issues/new?template=documentation.yaml
    about: Suggest improvements or report issues with gitmoji-pre-commit documentation
  - name: ğŸ› Bug Report
    url: https://github.com/HomerusJa/gitmoji-pre-commit/issues/new?template=bug_report.yaml
    about: File a bug report for gitmoji-pre-commit
  - name: ğŸš€ Feature Request
    url: https://github.com/HomerusJa/gitmoji-pre-commit/issues/new?template=feature_request.yaml
    about: Suggest a new feature or enhancement for gitmoji-pre-commit
  - name: ğŸ”’ Security
    url: https://github.com/HomerusJa/gitmoji-pre-commit/issues/new?template=security.yaml
    about: Report a security issue
  - name: ğŸ”§ Maintenance
    url: https://github.com/HomerusJa/gitmoji-pre-commit/issues/new?template=maintenance.yaml
    about: Report a maintenance issue
